import test from 'node:test';import assert from 'node:assert/strict';import {PETS} from './data.js';import {ensureCollection,discoveryOdds,purchaseDiscovery,switchCreature,isFinal,evolutionPrice,removeCreature,salePrice} from './collection.js';
const make=coins=>({coins,pet:{species:'lumio',name:'Mi Lumio',stage:2,primary:'#123456',secondary:'#654321',owned:['hat'],accessories:['hat']}});
test('Legacy migration and JSON reload preserve active copy, name, colours and accessories',()=>{const p=make(1200);p.creatures={lumio:{...p.pet}};ensureCollection(p);assert.equal(p.creatures.lumio,p.pet);const restored=JSON.parse(JSON.stringify(p));ensureCollection(restored);assert.equal(restored.creatures.lumio,restored.pet);assert.equal(restored.pet.primary,'#123456');});
test('Fixed probabilities remain 35/30/20/12/3 after owning duplicates',()=>{const p=make(3000);assert.deepEqual(discoveryOdds(p).map(o=>o.probability),[.35,.30,.20,.12,.03]);purchaseDiscovery(p,()=>0);p.discovery.seenAt='seen';purchaseDiscovery(p,()=>0);assert.deepEqual(discoveryOdds(p).map(o=>o.probability),[.35,.30,.20,.12,.03]);});
test('150 VC duplicate purchases have unique IDs and independent personalisation',()=>{const p=make(1000),a=purchaseDiscovery(p,()=>0);assert(a.ok);assert.equal(p.coins,850);assert.equal(purchaseDiscovery(p).reason,'pending');p.discovery.seenAt='seen';const b=purchaseDiscovery(p,()=>0);assert(b.ok);assert.equal(p.coins,700);assert.notEqual(a.creature.instanceId,b.creature.instanceId);assert.equal(a.creature.species,b.creature.species);a.creature.name='Uno';a.creature.primary='#abcdef';a.creature.stage=1;assert.equal(b.creature.stage,0);assert(switchCreature(p,a.creature.instanceId));assert.equal(p.pet.name,'Uno');assert(isFinal(p));assert(switchCreature(p,b.creature.instanceId));assert.equal(p.pet.name,'Luma');assert.equal(evolutionPrice(p),350);assert(switchCreature(p,'lumio'));assert.equal(p.pet.primary,'#123456');});
test('Sales/deletion protect starter, active and unopened receipt; never touch another copy',()=>{const p=make(2000);ensureCollection(p);assert(!removeCreature(p,'lumio',true).ok);const a=purchaseDiscovery(p,()=>0);assert(!removeCreature(p,a.creature.instanceId,true).ok);p.discovery.seenAt='seen';const b=purchaseDiscovery(p,()=>0);p.discovery.seenAt='seen';switchCreature(p,a.creature.instanceId);assert(!removeCreature(p,a.creature.instanceId,true).ok);const before=p.coins;assert.equal(removeCreature(p,b.creature.instanceId,true).refund,80);assert.equal(p.coins,before+80);assert(p.creatures[a.creature.instanceId]);assert(!removeCreature(p,b.creature.instanceId,true).ok);switchCreature(p,'lumio');assert(!removeCreature(p,a.creature.instanceId,false).ok);assert(removeCreature(p,a.creature.instanceId,true).ok);assert.equal(p.coins,before+160);assert.equal(salePrice({species:'astra'}),300);});
test('Insufficient funds never charge; eight species retain 3/2 stage structure',()=>{const p=make(149);assert.equal(purchaseDiscovery(p).reason,'coins');assert.equal(p.coins,149);assert.equal(PETS.filter(d=>!d.collectible).length,3);assert(PETS.filter(d=>!d.collectible).every(d=>d.stages.length===3));assert.equal(PETS.filter(d=>d.collectible).length,5);assert(PETS.filter(d=>d.collectible).every(d=>d.stages.length===2));});

test('700 VC starter change creates baby, preserves former evolution and blocks insufficient balance',async()=>{const {purchaseStarter}=await import('./collection.js');const p={coins:1000,pet:{instanceId:'old',species:'lumio',stage:2,name:'Antiguo',primary:'#ee1122',accessories:[]}};const result=purchaseStarter(p,'nyx');assert(result.ok);assert.equal(p.coins,300);assert.equal(p.pet.stage,0);assert.equal(p.creatures.old.stage,2);assert.equal(p.creatures.old.primary,'#ee1122');assert.equal(purchaseStarter(p,'bruma').ok,false);assert.equal(p.coins,300);});

test('Batch purchases charge 150 each and reserve all capacity atomically',async()=>{const {purchaseDiscoveries,finishDiscoveries}=await import('./collection.js');const p=make(10000);ensureCollection(p);const a=purchaseDiscoveries(p,10,()=>0);assert(a.ok);assert.equal(a.results.length,10);assert.equal(p.coins,8500);assert.equal(Object.keys(p.creatures).length,11);assert.equal(new Set(a.results.map(r=>r.creature.instanceId)).size,10);assert.equal(purchaseDiscoveries(p,5).reason,'pending');finishDiscoveries(p);assert(purchaseDiscoveries(p,10,()=>0).ok);finishDiscoveries(p);const before=p.coins;assert.equal(purchaseDiscoveries(p,10).reason,'capacity');assert.equal(p.coins,before);assert.equal(Object.keys(p.creatures).length,21);assert(purchaseDiscoveries(p,5,()=>0).ok);});
test('Direct and bulk sale refund once, preserve discovered catalog, protect active/starter',async()=>{const {purchaseDiscoveries,sellDiscovered,sellCreatures,finishDiscoveries}=await import('./collection.js');const p=make(3000),batch=purchaseDiscoveries(p,5,()=>0),ids=batch.results.map(r=>r.creature.instanceId);assert.equal(sellDiscovered(p,ids[0]).refund,80);assert(!sellDiscovered(p,ids[0]).ok);finishDiscoveries(p);const coins=p.coins;assert(!sellCreatures(p,['lumio',ids[1]]).ok);assert.equal(p.coins,coins);assert.equal(sellCreatures(p,[ids[1],ids[1],ids[2]]).refund,160);assert(p.discoveredSpecies.includes('luma'));assert.equal(Object.keys(p.creatures).length,3);switchCreature(p,ids[3]);assert(!sellCreatures(p,[ids[3],ids[4]]).ok);});
