import {rgbHsl,pigmentRegion,shadeTo,regionCenters,classifyBody} from './colour-layers.js';
import {PETS} from './data.js';
// The generated illustration is cropped and recoloured at runtime. No filter is
// applied to the complete image: eyes, ink, highlights and neutral details stay put.
import {anatomyFor} from './anatomy.js';
const load=path=>{const image=new Image();const ready=new Promise((resolve,reject)=>{image.onload=()=>resolve(image);image.onerror=()=>reject(Error('No se han podido cargar las criaturas.'));});image.src=new URL(path,import.meta.url).href;return ready;};
const atlases={starters:load('./assets/starters-v6.png'),collectors:load('./assets/collectors-v6.png')};

const base={lumio:['#ed817a','#ffe5a8'],nyx:['#68b6e7','#ffe195'],bruma:['#9dcc69','#b47bdd'],luma:['#b391e5','#f6bea6'],nimbo:['#78cdbd','#ffda76'],gema:['#eeaa91','#68bdc3'],vesper:['#8582ce','#e6a1bd'],astra:['#e8ba57','#b299df']};
const cache=new Map(),pixels=new Map();
// Remove clipped pieces of neighbouring cells without flattening the illustration.
function isolateSprite(data,threshold=16){const w=data.width,h=data.height,labels=new Int32Array(w*h),queue=new Int32Array(w*h);let label=0,best=0,bestSize=0;for(let start=0;start<labels.length;start++){if(labels[start]||data.data[start*4+3]<threshold)continue;label++;let head=0,tail=1;queue[0]=start;labels[start]=label;while(head<tail){const n=queue[head++],x=n%w,y=Math.floor(n/w);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const nx=x+dx,ny=y+dy;if(nx<0||nx>=w||ny<0||ny>=h)continue;const next=ny*w+nx;if(!labels[next]&&data.data[next*4+3]>=threshold){labels[next]=label;queue[tail++]=next;}}}if(tail>bestSize){bestSize=tail;best=label;}}for(let n=0;n<labels.length;n++){if(labels[n]===best)continue;const x=n%w,y=Math.floor(n/w);let edge=false;if(labels[n]===0)for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const nx=x+dx,ny=y+dy;if(nx>=0&&nx<w&&ny>=0&&ny<h&&labels[ny*w+nx]===best)edge=true;}if(!edge)data.data[n*4+3]=0;}}
async function source(species,stage){const key=`${species}:${stage}`;if(pixels.has(key))return pixels.get(key);const parts=anatomyFor(species,stage),atlas=await atlases[parts.atlas],[x,y,right,bottom]=parts.box,c=document.createElement('canvas');c.width=400;c.height=440;const ctx=c.getContext('2d',{willReadFrequently:true});const crop=document.createElement('canvas');crop.width=right-x;crop.height=bottom-y;const cropCtx=crop.getContext('2d',{willReadFrequently:true});cropCtx.drawImage(atlas,x,y,right-x,bottom-y,0,0,crop.width,crop.height);const isolated=cropCtx.getImageData(0,0,crop.width,crop.height);isolateSprite(isolated,100);cropCtx.putImageData(isolated,0,0);ctx.drawImage(crop,parts.offsetX,parts.offsetY,crop.width*parts.scale,crop.height*parts.scale);const data=ctx.getImageData(0,0,400,440);isolateSprite(data);for(let i=3;i<data.data.length;i+=4){if(data.data[i]>=245)data.data[i]=255;else if(data.data[i]<=3)data.data[i]=0;}const regions=new Int8Array(400*440).fill(-1);for(let i=0;i<data.data.length;i+=4)if(data.data[i+3]>20){regions[i/4]=pigmentRegion(species,[...data.data.slice(i,i+3)]);}// Protect antialiased ink next to a dark outline, without freezing isolated body shadows.
for(let n=0;n<regions.length;n++){if(regions[n]!==0)continue;const [h,s,l]=rgbHsl(...data.data.slice(n*4,n*4+3));if(h<250||h>310||l>.45)continue;const x=n%400,y=Math.floor(n/400);let ink=false;for(let dy=-1;dy<=1&&!ink;dy++)for(let dx=-1;dx<=1;dx++){if(x+dx<0||x+dx>=400||y+dy<0||y+dy>=440)continue;const at=((y+dy)*400+x+dx)*4,[nh,ns,nl]=rgbHsl(...data.data.slice(at,at+3));if(data.data[at+3]>200&&nh>=250&&nh<=310&&nl<.22){ink=true;break;}}if(ink)regions[n]=-1;}
const centers=regionCenters(data.data,regions,base[species]);const value={data,regions,parts,centers,species};pixels.set(key,value);return value;}
function layer(data,predicate){const c=document.createElement('canvas');c.width=data.width;c.height=data.height;const out=new ImageData(new Uint8ClampedArray(data.data),data.width,data.height);for(let n=0;n<out.data.length;n+=4)if(!predicate((n/4)%data.width,Math.floor(n/4/data.width)))out.data[n+3]=0;c.getContext('2d').putImageData(out,0,0);return c;}
function bodyLayers(data,parts){return Object.fromEntries(['head','torso','wrists'].map(part=>[part,layer(data,(x,y)=>classifyBody(parts,x,y)===part)]));}
// Pigment and outline are independent layers. Head/body/forelimb masks control occlusion.
function recolourLayers(src,colors){const out=new ImageData(new Uint8ClampedArray(src.data.data),400,440),pigments=[new Uint8ClampedArray(out.data.length),new Uint8ClampedArray(out.data.length)],outlinePixels=new Uint8ClampedArray(out.data.length),neutralPixels=new Uint8ClampedArray(out.data.length);for(let i=0;i<out.data.length;i+=4){const part=src.regions[i/4];if(part>=0){const rgb=colors[part].toLowerCase()===base[src.species][part]?out.data.slice(i,i+3):shadeTo([...out.data.slice(i,i+3)],colors[part],src.centers[part]);out.data.set(rgb,i);pigments[part].set(out.data.slice(i,i+4),i);}else{const rgb=out.data.slice(i,i+3),ink=Math.max(...rgb)<145&&rgbHsl(...rgb)[2]<.34;(ink?outlinePixels:neutralPixels).set(out.data.slice(i,i+4),i);}}return {data:out,primary:new ImageData(pigments[0],400,440),secondary:new ImageData(pigments[1],400,440),outline:new ImageData(outlinePixels,400,440),neutralDetails:new ImageData(neutralPixels,400,440)};}
export async function petImage(config={}){const species=PETS.some(p=>p.id===config.species)?config.species:'lumio',stage=Math.max(0,Math.min((PETS.find(p=>p.id===species)?.stages.length||3)-1,Number(config.stage)||0)),def=PETS.find(p=>p.id===species),safe=(v,f)=>/^#[\da-f]{6}$/i.test(v||'')?v:f,colors=[safe(config.primary,def.primary),def.secondary],items=[],key=JSON.stringify([species,stage,colors,items,config.accessorySettings||{}]);if(cache.has(key)){const cached=cache.get(key);cache.delete(key);cache.set(key,cached);return cached;}const c=document.createElement('canvas');c.width=400;c.height=440;const ctx=c.getContext('2d'),src=await source(species,stage),out=recolourLayers(src,colors).data;ctx.putImageData(out,0,0);const url=c.toDataURL('image/png');cache.set(key,url);if(cache.size>60)cache.delete(cache.keys().next().value);return url;}
export function paintPets(root=document){root.querySelectorAll('[data-pet]').forEach(el=>{const token=el.dataset.pet;petImage(JSON.parse(token)).then(url=>{if(el.isConnected&&el.dataset.pet===token)el.src=url;}).catch(()=>{el.alt='Criatura no disponible. Recarga para volver a intentarlo.';});});}
// Diagnostic/export surface: separate pigment, ink, neutral and physical-body layers.
export async function petLayerImages(config={}){const def=PETS.find(p=>p.id===config.species)||PETS[0],stage=Math.max(0,Math.min(def.stages.length-1,Number(config.stage)||0)),src=await source(def.id,stage),colors=[config.primary||def.primary,config.secondary||def.secondary],layers=recolourLayers(src,colors),parts=bodyLayers(layers.data,src.parts),result={};for(const name of ['primary','secondary','outline','neutralDetails']){const c=document.createElement('canvas');c.width=400;c.height=440;c.getContext('2d').putImageData(layers[name],0,0);result[name]=c.toDataURL('image/png');}for(const [name,c] of Object.entries(parts))result[name]=c.toDataURL('image/png');return result;}
