import webpush from 'web-push';
import {readFile,mkdir,writeFile,rename} from 'node:fs/promises';
import {randomUUID,createHmac,timingSafeEqual} from 'node:crypto';
import {resolve} from 'node:path';
import {reminderMessages,madridDate} from './reminders.js';
export function allowedPushEndpoint(endpoint){try{const u=new URL(endpoint);return u.protocol==='https:'&&!u.username&&!u.password&&(!u.port||u.port==='443')&&(u.hostname==='fcm.googleapis.com'||u.hostname==='updates.push.services.mozilla.com'||u.hostname.endsWith('.push.services.mozilla.com')||u.hostname==='web.push.apple.com'||u.hostname.endsWith('.push.apple.com'));}catch{return false;}}
export async function createPushService({directory=resolve('.runtime'),send=webpush.sendNotification.bind(webpush),now=()=>new Date()}={}){await mkdir(directory,{recursive:true,mode:0o700});const file=resolve(directory,'push.json');let state;try{state=JSON.parse(await readFile(file,'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;state={keys:webpush.generateVAPIDKeys(),secret:randomUUID()+randomUUID(),devices:{}};}let writing=Promise.resolve();function persist(){const serialized=JSON.stringify(state);writing=writing.then(async()=>{await writeFile(file+'.tmp',serialized,{mode:0o600});await rename(file+'.tmp',file);});return writing;}await persist();const subject=process.env.VAPID_SUBJECT||'https://verbquest-aaron-demo.tribuiagenius.chatgpt.site';webpush.setVapidDetails(subject,state.keys.publicKey,state.keys.privateKey);
 const sign=id=>createHmac('sha256',state.secret).update(id).digest('base64url');function deviceId(req){const raw=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('vq_device='))?.slice(10);if(!raw)return null;const [id,sig]=raw.split('.');if(!id||!sig)return null;const expected=sign(id);return sig.length===expected.length&&timingSafeEqual(Buffer.from(sig),Buffer.from(expected))?id:null;}
 async function body(req){let value='',size=0;for await(const chunk of req){size+=chunk.length;if(size>12000)throw Error('Solicitud demasiado grande');value+=chunk;}return JSON.parse(value||'{}');}
 function json(res,code,data){res.writeHead(code,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
 async function tick(){const date=now(),hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Madrid',hour:'2-digit',hourCycle:'h23'}).format(date));if(hour<18)return;let changed=false;for(const [id,device] of Object.entries(state.devices)){const messages=reminderMessages(device,date),message=messages.find(m=>m.tag.startsWith('exam:')&&!device.sent.includes(m.tag))||messages.find(m=>!device.sent.includes(m.tag));if(!message||device.sent.some(t=>t===`delivery:${madridDate(date)}`))continue;try{await send(device.subscription,JSON.stringify(message),{TTL:3600,timeout:10000});device.sent.push(message.tag,`delivery:${madridDate(date)}`);device.sent=device.sent.slice(-90);changed=true;}catch(e){if([404,410].includes(e.statusCode)){delete state.devices[id];changed=true;}else console.warn('No se pudo entregar un aviso; se reintentará.');}}if(changed)await persist();}
 async function handle(req,res,path){if(!path.startsWith('/api/push/'))return false;try{if(req.method==='GET'&&path==='/api/push/config'){let id=deviceId(req);if(!id&&new URL(req.url,'http://local').searchParams.get('register')==='1'){id=randomUUID();res.setHeader('Set-Cookie',`vq_device=${id}.${sign(id)}; HttpOnly; SameSite=Strict; Path=/api/push; Max-Age=31536000${process.env.VERBQUEST_HTTPS==='1'?'; Secure':''}`);}json(res,200,{enabled:true,publicKey:state.keys.publicKey});return true;}const origin=req.headers.origin,host=req.headers.host;if(!origin||new URL(origin).host!==host){json(res,403,{error:'Origen no permitido'});return true;}const id=deviceId(req);if(!id){json(res,401,{error:'Activa primero los avisos de este dispositivo'});return true;}if(req.method==='POST'&&path==='/api/push/subscribe'){const d=await body(req),sub=d.subscription;if(!allowedPushEndpoint(sub?.endpoint)||!/^[A-Za-z0-9_-]{80,100}$/.test(sub?.keys?.p256dh||'')||!/^[A-Za-z0-9_-]{20,30}$/.test(sub?.keys?.auth||'')){json(res,400,{error:'Suscripción inválida'});return true;}if(!state.devices[id]&&Object.keys(state.devices).length>=500){json(res,503,{error:'No se pueden registrar más dispositivos'});return true;}const previous=Object.values(state.devices).find(x=>x.subscription.endpoint===sub.endpoint);for(const [otherId,device] of Object.entries(state.devices))if(otherId!==id&&device.subscription.endpoint===sub.endpoint)delete state.devices[otherId];state.devices[id]={subscription:sub,notifications:{daily:d.preferences?.daily===true,exams:d.preferences?.exams===true},lastPractice:d.lastPractice||null,sent:previous?.sent||[]};await persist();json(res,200,{subscribed:true});return true;}if(req.method==='POST'&&path==='/api/push/preferences'){const d=await body(req),device=state.devices[id];if(device){device.notifications={daily:d.preferences?.daily===true,exams:d.preferences?.exams===true};device.lastPractice=/^\d{4}-\d{2}-\d{2}$/.test(d.lastPractice||'')?d.lastPractice:null;await persist();}json(res,200,{saved:!!device});return true;}if(req.method==='DELETE'&&path==='/api/push/subscribe'){delete state.devices[id];await persist();json(res,200,{subscribed:false});return true;}json(res,404,{error:'Ruta no disponible'});}catch{json(res,400,{error:'No se pudo guardar la suscripción'});}return true;}
 return {handle,tick};}
